#!/usr/bin/env bash
#===================================================================================
# LABADMIN 
#         FILE: labadmin-netauto
#
#  DESCRIPTION: Automatically set UP first network interface and config using DHCP
#
#       AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#	     LICENSE: GNU General Public License v3.0
#      VERSION: 2026.06
#      CREATED: 2026.06.01
#===================================================================================

opt="$1"

# INSTALL SERVICE
if [ "$1" = "--install" ]; then
  echo '[Unit]
  Description=Labadmin auto network up on first interface
  After=network-pre.target
  Before=network.target
  
  [Service]
  Type=oneshot
  ExecStart=/opt/labadmin-linux-tools/labadmin-netauto
  RemainAfterExit=yes
  
  [Install]
  WantedBy=multi-user.target
  ' > /etc/systemd/system/labadmin-netauto.service
  
  systemctl daemon-reload
  systemctl enable labadmin-netauto.service

# EXEC NETAUTO
else
  iface=$(ip -c=never -o link show | grep -Eo "^[0-9]: [[:alnum:]]+" | cut -f2 -d" " | egrep -v "^lo|^w" | head -1)
  ip link set "$iface" up
  dhclient "$iface"
fi



